
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 16 21:50:57 CST 2024
//----------------------------------------------------

package com.luis.proyectoservidor.parser;

import com.luis.proyectoservidor.lexer.AccionesLexer;
import com.luis.proyectoservidor.objetos.*;
import java_cup.runtime.*;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Apr 16 21:50:57 CST 2024
  */
public class AccionesParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AccionesParser() {super();}

  /** Constructor which sets the default scanner. */
  public AccionesParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AccionesParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\066\005\001\002\000\004\002\006\001" +
    "\002\000\004\002\000\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AccionesParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AccionesParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AccionesParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    // Connect this parser to a scanner!
    public AccionesParser(AccionesLexer lex) {
	    super(lex);
	  }
    private Symbol s;

    public ArrayList<ErrorSintactico> errores = new ArrayList<>();


public void syntax_error(Symbol c) {
            this.s = c;
            String cadena = c.value.toString();
            int linea = c.left;
            int col = c.right;
            System.out.print("Error aca, value: " + cadena);
            System.out.print(" -Linea " + linea);
            System.out.println(" Columna " + col);
                 errores.add(new ErrorSintactico(cadena, linea, col, "Error sintáctico"));
            if (expected_token_ids().isEmpty()) {
                System.out.println("ya no se esperaba ningun simbolo");
            }
        }
    public Symbol getSim(){
        return this.s;
    }

    public void unrecovered_syntax_error(Symbol c) {
        System.out.println("Error irrecuperable sobrecargado");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AccionesParser$actions {
  private final AccionesParser parser;

  /** Constructor */
  CUP$AccionesParser$actions(AccionesParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AccionesParser$do_action(
    int                        CUP$AccionesParser$act_num,
    java_cup.runtime.lr_parser CUP$AccionesParser$parser,
    java.util.Stack            CUP$AccionesParser$stack,
    int                        CUP$AccionesParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AccionesParser$result;

      /* select the action based on the action number */
      switch (CUP$AccionesParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // acciones ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$AccionesParser$result = parser.getSymbolFactory().newSymbol("acciones",0, ((java_cup.runtime.Symbol)CUP$AccionesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$AccionesParser$stack.peek()), RESULT);
            }
          return CUP$AccionesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= acciones EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AccionesParser$stack.elementAt(CUP$AccionesParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AccionesParser$stack.elementAt(CUP$AccionesParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AccionesParser$stack.elementAt(CUP$AccionesParser$top-1)).value;
		RESULT = start_val;
              CUP$AccionesParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AccionesParser$stack.elementAt(CUP$AccionesParser$top-1)), ((java_cup.runtime.Symbol)CUP$AccionesParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AccionesParser$parser.done_parsing();
          return CUP$AccionesParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

