
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 22 01:26:42 CST 2024
//----------------------------------------------------

package com.luis.proyectoservidor.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 15;
  public static final int NUMERO = 57;
  public static final int COMPONENTE_IMAGEN = 41;
  public static final int ACCION_BORRAR_COMPONENTE = 34;
  public static final int PARAMETRO_FECHA_MODIFICACION = 22;
  public static final int PARAMETROS = 4;
  public static final int COMPONENTE_VIDEO = 45;
  public static final int PARAMETRO_SITIO = 27;
  public static final int ACCION_NUEVA_PAGINA = 25;
  public static final int NOMBRE = 6;
  public static final int CORCHETE_C = 48;
  public static final int ATRIBUTO_ANCHO = 44;
  public static final int PARAMETRO_ID = 18;
  public static final int ETIQUETAS = 8;
  public static final int ACCION_MODIFICAR_PAGINA = 30;
  public static final int FECHA = 51;
  public static final int CORCHETE_A = 47;
  public static final int PARAMETRO_FECHA_CREACION = 21;
  public static final int ATRIBUTO_ORIGEN = 42;
  public static final int ACCION_BORRAR_PAGINA = 29;
  public static final int IDENTIFICADOR = 50;
  public static final int IGUAL = 14;
  public static final int ACCION_MODIFICAR_COMPONENTE = 20;
  public static final int COMP_TITULO = 35;
  public static final int PARAMETRO_USUARIO_MODIFICACION = 23;
  public static final int ATRIBUTO_ALINEACION = 37;
  public static final int ATRIBUTO_ALTURA = 43;
  public static final int PARAMETRO_PAGINA = 32;
  public static final int EOF = 0;
  public static final int ATRIBUTO_ETIQUETAS = 54;
  public static final int COMILLA = 55;
  public static final int error = 1;
  public static final int PARAMETRO_USUARIO_CREACION = 19;
  public static final int CADENA = 53;
  public static final int MENOR = 12;
  public static final int ATRIBUTOS = 10;
  public static final int ATRIBUTO = 11;
  public static final int ACCION = 3;
  public static final int PARAMETRO_PADRE = 28;
  public static final int MAYOR = 13;
  public static final int BARRA = 56;
  public static final int IDES = 58;
  public static final int VALOR = 7;
  public static final int ATRIBUTO_COLOR = 39;
  public static final int ACCION_AGREGAR_COMPONENTE = 31;
  public static final int ACCION_NUEVO_SITIO = 17;
  public static final int PARAMETRO_CLASE = 33;
  public static final int CERRAR = 16;
  public static final int COLOR_HEXAGONAL = 52;
  public static final int PARAMETRO_TITULO = 26;
  public static final int COMP_PARRAFO = 40;
  public static final int PARAMETRO = 5;
  public static final int ACCIONES = 2;
  public static final int ACCION_BORRAR_SITIO_WEB = 24;
  public static final int TEXTO = 49;
  public static final int ETIQUETA = 9;
  public static final int VALOR_ALINEACION = 38;
  public static final int COMPONENTE_MENU = 46;
  public static final int ATRIBUTO_TEXTO = 36;
}

