
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 16 00:02:02 CST 2024
//----------------------------------------------------

package com.luis.proyectoservidor.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 14;
  public static final int NUMERO = 53;
  public static final int VALOR_ATRIBUTO_DERECHA = 37;
  public static final int COMPONENTE_IMAGEN = 41;
  public static final int ACCION_BORRAR_COMPONENTE = 31;
  public static final int PARAMETRO_FECHA_MODIFICACION = 19;
  public static final int PARAMETROS = 4;
  public static final int COMPONENTE_VIDEO = 45;
  public static final int VALOR_ATRIBUTO_JUSTIFICAR = 38;
  public static final int PARAMETRO_SITIO = 24;
  public static final int ACCION_NUEVA_PAGINA = 22;
  public static final int NOMBRE = 6;
  public static final int CORCHETE_C = 48;
  public static final int ATRIBUTO_ANCHO = 44;
  public static final int PARAMETRO_ID = 16;
  public static final int ETIQUETAS = 8;
  public static final int ACCION_MODIFICAR_PAGINA = 27;
  public static final int FECHA = 51;
  public static final int CORCHETE_A = 47;
  public static final int PARAMETRO_FECHA_CREACION = 18;
  public static final int ATRIBUTO_ORIGEN = 42;
  public static final int ACCION_BORRAR_PAGINA = 26;
  public static final int IDENTIFICADOR = 50;
  public static final int IGUAL = 13;
  public static final int COMP_TITULO = 32;
  public static final int PARAMETRO_USUARIO_MODIFICACION = 20;
  public static final int ATRIBUTO_ALINEACION = 34;
  public static final int ATRIBUTO_ALTURA = 43;
  public static final int PARAMETRO_PAGINA = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PARAMETRO_USUARIO_CREACION = 17;
  public static final int MAYOR_QUE = 12;
  public static final int ATRIBUTOS = 9;
  public static final int ATRIBUTO = 10;
  public static final int ACCION = 3;
  public static final int VALOR_ATRIBUTO_CENTRAR = 35;
  public static final int PARAMETRO_PADRE = 25;
  public static final int VALOR = 7;
  public static final int ATRIBUTO_COLOR = 39;
  public static final int ACCION_AGREGAR_COMPONENTE = 28;
  public static final int ACCION_NUEVO_SITIO = 15;
  public static final int PARAMETRO_CLASE = 30;
  public static final int COLOR_HEXAGONAL = 52;
  public static final int PARAMETRO_TITULO = 23;
  public static final int COMP_PARRAFO = 40;
  public static final int PARAMETRO = 5;
  public static final int ACCIONES = 2;
  public static final int VALOR_ATRIBUTO_IZQUIERDA = 36;
  public static final int MENOR_QUE = 11;
  public static final int ACCION_BORRAR_SITIO_WEB = 21;
  public static final int TEXTO = 49;
  public static final int COMPONENTE_MENU = 46;
  public static final int ATRIBUTO_TEXTO = 33;
}

